log:
  level: DEBUG

mongo:
  db: template77
  host: 10.0.0.10
  port: 27017
  username:
  password:

mysql:
  db: template77
  host: 127.0.0.1
  port: 3306
  username: template7
  password: password
  root: root
  rootPassword:

backend:
  username: "admin"
  password: "password"
  endpoint: "http://localhost:8080"